 alias ls="ls --color=auto"
 alias ll="ls -lhA"
 alias la="ls -hA"
 alias guimat="synclient HorizTwoFingerScroll=0 && /usr/local/MATLAB/R2014a/bin/matlab & disown"
 alias mwin="mount /dev/sda4"
 alias dls="cd /home/callum/Downloads"
 alias videos="cd /home/callum/videos"
 alias dropbox="cd /home/callum/Dropbox"
 alias summer="cd /home/callum/Dropbox/Public/work/4th\ year/Summer"
 alias tdvp="cd /home/callum/Dropbox/TDVP_CPS"
 alias ipy="ipython qtconsole --pylab=inline --style=solarized & disown"
#  alias fuck="sudo $(history | tail -n 1 | awk '{ print $4, $NF }' )"
 alias cps="cd /home/callum/Dropbox/TDVP_CPS"
